In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
# data = pd.read_csv(r'/content/amazon.csv', encoding='latin1')

In [4]:
# data.to_csv("/content/drive/MyDrive/csv_file/mydata8.csv")

In [5]:
data = pd.read_csv(r'/content/drive/MyDrive/csv_file/mydata8.csv',parse_dates=['date'])

In [6]:
data.dtypes

Unnamed: 0             int64
year                   int64
state                 object
month                 object
number               float64
date          datetime64[ns]
dtype: object

1. Display Top 5 Rows of The Dataset

In [7]:
data.head()

   Unnamed: 0  year state    month  number       date
0           0  1998  Acre  Janeiro     0.0 1998-01-01
1           1  1999  Acre  Janeiro     0.0 1999-01-01
2           2  2000  Acre  Janeiro     0.0 2000-01-01
3           3  2001  Acre  Janeiro     0.0 2001-01-01
4           4  2002  Acre  Janeiro     0.0 2002-01-01

2. Check Last 5 Rows

In [8]:
data.tail()

      Unnamed: 0  year      state     month  number       date
6449        6449  2012  Tocantins  Dezembro   128.0 2012-01-01
6450        6450  2013  Tocantins  Dezembro    85.0 2013-01-01
6451        6451  2014  Tocantins  Dezembro   223.0 2014-01-01
6452        6452  2015  Tocantins  Dezembro   373.0 2015-01-01
6453        6453  2016  Tocantins  Dezembro   119.0 2016-01-01

3. Find Shape of Our Dataset (Number of Rows And Number of Columns)

In [9]:
data.shape

(6454, 6)

4. Getting Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  6454 non-null   int64
 1   year        6454 non-null   int64
 2   state       6454 non-null   object
 3   month       6454 non-null   object
 4   number      6454 non-null   float64
 5   date        6454 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 302.7+ KB

5. Check For Duplicate Data and Drop Them

In [11]:
dup_data = data.duplicated().any()

In [12]:
dup_data

np.False_

In [13]:
data = data.drop_duplicates()

In [14]:
data.shape

(6454, 6)

6. Check Null Values In The Dataset

In [15]:
data.isnull().sum()

Unnamed: 0    0
year          0
state         0
month         0
number        0
date          0
dtype: int64

7. Get Overall Statistics About The Dataframe

In [16]:
data.describe()

        Unnamed: 0         year       number                           date
count  6454.000000  6454.000000  6454.000000                           6454
mean   3226.500000  2007.461729   108.293163  2007-06-18 18:28:53.622559488
min       0.000000  1998.000000     0.000000            1998-01-01 00:00:00
25%    1613.250000  2002.000000     3.000000            2002-01-01 00:00:00
50%    3226.500000  2007.000000    24.000000            2007-01-01 00:00:00
75%    4839.750000  2012.000000   113.000000            2012-01-01 00:00:00
max    6453.000000  2017.000000   998.000000            2017-01-01 00:00:00
std    1863.253651     5.746654   190.812242                            NaN

8. Rename Month Names To English

In [17]:
data['month'].unique()

array(['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

In [18]:
data['month_now'] = data['month'].map({'Janeiro':'Jan','Fevereiro':'Feb','Março':'Mar','Abril':'Apr','Maio':'May','Junho':'Jun','Julho':'Jul','Agosto':'Aug','Setembro':'Sep','Outubro':'Oct','Novembro':'Nov','Dezembro':'Dec'})

In [19]:
data.head()

   Unnamed: 0  year state    month  number       date month_now
0           0  1998  Acre  Janeiro     0.0 1998-01-01       Jan
1           1  1999  Acre  Janeiro     0.0 1999-01-01       Jan
2           2  2000  Acre  Janeiro     0.0 2000-01-01       Jan
3           3  2001  Acre  Janeiro     0.0 2001-01-01       Jan
4           4  2002  Acre  Janeiro     0.0 2002-01-01       Jan

9. Total Number of Fires Registered

In [20]:
data.shape

(6454, 7)

In [21]:
print("Total Number of Fires Registered",data.shape[0])

Total Number of Fires Registered 6454

10. In Which Month Maximum Number of Forest Fires Were Reported?

In [22]:
data.columns

Index(['Unnamed: 0', 'year', 'state', 'month', 'number', 'date', 'month_now'], dtype='object')

In [23]:
data.groupby('month_now')['number'].sum().sort_values(ascending=False)

month_now
Jul    92326.113
Oct    88681.579
Aug    88050.435
Nov    85508.054
Sep    58578.305
Dec    57535.480
Jun    56010.675
Jan    47747.844
May    34731.363
Feb    30848.050
Mar    30717.405
Apr    28188.770
Name: number, dtype: float64

11. In Which Year Maximum Number of Forest Fires Was Reported?

In [37]:
data.groupby('year')['number'].sum().sort_values(ascending=False).reset_index()

    year     number
0   2003  42760.674
1   2016  42212.229
2   2015  41208.292
3   2012  40084.860
4   2014  39621.183
5   2009  39117.178
6   2004  38453.163
7   2002  37390.600
8   2010  37037.449
9   2017  36685.624
10  2013  35146.118
11  2005  35004.965
12  2011  34633.545
13  2006  33832.161
14  2007  33037.413
15  2008  29378.964
16  2001  29071.612
17  2000  27351.251
18  1999  26882.821
19  1998  20013.971

12. In Which State Maximum Number of Forest Fires Was Reported?

In [26]:
data.groupby('state')['number'].sum().sort_values(ascending = False)

state
Mato Grosso         96246.028
Paraiba             52435.918
Sao Paulo           51121.198
Rio                 45160.865
Bahia               44746.226
Piau                37803.747
Goias               37695.520
Minas Gerais        37475.258
Tocantins           33707.885
Amazonas            30650.129
Ceara               30428.063
Maranhao            25129.131
Pará                24512.144
Pernambuco          24498.000
Roraima             24385.074
Santa Catarina      24359.852
Amapa               21831.576
Rondonia            20285.429
Acre                18464.030
Espirito Santo       6546.000
Alagoas              4644.000
Distrito Federal     3561.000
Sergipe              3237.000
Name: number, dtype: float64

13. Find Total Number of Fires Were Reported In Amazonas

In [ ]:
data

In [27]:
[data['state'] == 'Amazonas']

[0       False
 1       False
 2       False
 3       False
 4       False
         ...
 6449    False
 6450    False
 6451    False
 6452    False
 6453    False
 Name: state, Length: 6454, dtype: bool]

In [29]:
data[data['state'] == 'Amazonas']['number'].sum()

np.float64(30650.129)

14. Display Number of Fires Were Reported In Amazonas (Year-Wise)

In [30]:
data[data['state'] == 'Amazonas'].groupby('year')['number'].sum()

year
1998     946.000
1999    1061.000
2000     853.000
2001    1297.000
2002    2852.000
2003    1524.268
2004    2298.207
2005    1657.128
2006     997.640
2007     589.601
2008    2717.000
2009    1320.601
2010    2324.508
2011    1652.538
2012    1110.641
2013     905.217
2014    2385.909
2015    1189.994
2016    2060.972
2017     906.905
Name: number, dtype: float64

15. Display Number of Fires Were Reported In Amazonas (Day-Wise)

In [32]:
data[data['state'] == 'Amazonas'].groupby(data['date'].dt.day)['number'].sum()

date
1    30650.129
Name: number, dtype: float64

16. Find Total Number of Fires  Were Reported In 2015 And Visualize Data Based on Each ‘Month’

In [35]:
data[data['year'] == 2015].groupby('month_now')['number'].sum().sort_values(ascending=False).reset_index()

   month_now    number
0        Jan  4635.000
1        Oct  4499.525
2        Jul  4364.392
3        Aug  4363.125
4        Dec  4088.522
5        Nov  4034.518
6        Jun  3260.552
7        Apr  2573.000
8        Sep  2494.658
9        May  2384.000
10       Feb  2309.000
11       Mar  2202.000

17. Find Average Number of Fires Were Reported From Highest to Lowest (State-Wise)

In [36]:
data.groupby('state')['number'].mean().sort_values(ascending=False).reset_index()

               state      number
0          Sao Paulo  213.896226
1        Mato Grosso  201.351523
2              Bahia  187.222703
3               Piau  158.174674
4              Goias  157.721841
5       Minas Gerais  156.800243
6          Tocantins  141.037176
7           Amazonas  128.243218
8              Ceara  127.314071
9            Paraiba  109.698573
10          Maranhao  105.142808
11              Pará  102.561272
12        Pernambuco  102.502092
13           Roraima  102.029598
14    Santa Catarina  101.924067
15             Amapa   91.345506
16          Rondonia   84.876272
17              Acre   77.255356
18               Rio   62.985865
19    Espirito Santo   27.389121
20           Alagoas   19.350000
21  Distrito Federal   14.899582
22           Sergipe   13.543933

18.  To Find The State Names Where Fires Were Reported In 'dec' Month

In [38]:
data[data['month_now'] == 'Dec']['state'].unique()

array(['Acre', 'Alagoas', 'Amapa', 'Amazonas', 'Bahia', 'Ceara',
       'Distrito Federal', 'Espirito Santo', 'Goias', 'Maranhao',
       'Mato Grosso', 'Minas Gerais', 'Pará', 'Paraiba', 'Pernambuco',
       'Piau', 'Rio', 'Rondonia', 'Roraima', 'Santa Catarina',
       'Sao Paulo', 'Sergipe', 'Tocantins'], dtype=object)